config/routes.rb
Rails.application.routes.draw do
  resources :cars

  resources :addresses

  resources :owners

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :owner
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :cars
  belongs_to :address
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:owner_id, :make, :model, :vin_number)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :address_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.number_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :vin_number %><br>
    <%= f.text_field :vin_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Make</th>
      <th>Model</th>
      <th>Vin number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.owner_id %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.vin_number %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @car.owner_id %>
</p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Vin number:</strong>
  <%= @car.vin_number %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MidtermPracticeS2015</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address_id %><br>
    <%= f.number_field :address_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.address_id %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @owner.address_id %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>